language: node_js
os: osx
addons:
  artifacts:
    target_paths: dmgfiles/*
    debug: true
jobs:  
  include:
    - stage: "CreateDMGApp"
      name: "CreateDMGAPP"
      script:
        - security import KatalonCodeSignDeveloperCert.p12 -k ~/Library/Keychains/login.keychain-db -P katalon@123
        - security find-identity -v
        - npm install create-dmg
        - create-dmg KatalonStudio.app