language: node_js
os: osx
node_js:
  - '10'
  - '8'
addons:
  artifacts:
    target_paths: dmgfiles/*
    debug: true
jobs:  
  include:
    - stage: "CreateDMG"
      name: "Creating"
      script:
        - ls -la
        - nvm install stable
        - npm install --global create-dmg
        - create-dmg KatalonStudio.app