language: node_js
os: osx
addons:
  artifacts:
    target_paths: dmgfiles/*
    debug: true
jobs:  
  include:
    - stage: "Importcertificate"
      name: "Importcertificate"
      script:
        - security import KatalonCodeSignDeveloperCert.p12 -k ~/Library/Keychains/login.keychain-db -P katalon@123
        - security find-identity -v
    - stage: "CreateDMG"
      name: "Creating"
      script:
        - npm install create-dmg
        - create-dmg KatalonStudio.app
