language: node_js
os: osx
node_js:
  - '10'
  - '8'
addons:
  artifacts:
    target_paths: dmgfiles/*
    debug: true
jobs:  
  include:
    - stage: "Importcertificate"
      name: "Importcertificate"
      script:
        - security import KatalonCodeSignDeveloperCert.p12 -k ~/Library/Keychains/login.keychain-db -P katalon@123
        - security find-identity -v
    - stage: "CreateDMG"
      name: "Creating"
      script:
        - ls -la
        - nvm install stable
        - npm install --global create-dmg
        - create-dmg KatalonStudio.app
