language: node_js
os: osx
addons:
  artifacts:
    target_paths: dmgfiles/*
    debug: true
jobs:  
  include:
    - stage: "CreateDMG"
      name: "Creating DMG"
      script: 
        - npm install --global create-dmg
        - create-dmg 'Katalon.Studio.app' dmgfiles/Katalon.Studio.dmg