language: node_js
os: osx
addons:
  artifacts:
    target_paths: Build/*
    debug: true
jobs:  
  include:
    - stage: "CreateDMGApp"
      name: "CreateDMGAPP"
      script:
        - security import KatalonCodeSignDeveloperCert.p12 -k ~/Library/Keychains/login.keychain-db -P katalon@123
        - security find-identity -v
        - mkdir ~/.npm-global
        - npm config set prefix '~/.npm-global'
        - export PATH=~/.npm-global/bin:$PATH
        - npm install -g create-dmg
        - mkdir -p Build
        - create-dmg KatalonStudio.app Build
